Repository CSID-DGU/2024-1-CECD4-TheRed-4, pull requests merged in 2024-11, with the labels that each got.

#58 [FEAT] 소켓 통신 및 자동매매 구현 완료
  back/build.gradle
  back/src/main/java/com/thered/stocksignal/app/controller/MainController.java
  back/src/main/java/com/thered/stocksignal/app/controller/ScenarioController.java
  back/src/main/java/com/thered/stocksignal/app/dto/CompanyDto.java
  back/src/main/java/com/thered/stocksignal/app/dto/ScenarioDto.java
  back/src/main/java/com/thered/stocksignal/app/dto/StockDto.java
  back/src/main/java/com/thered/stocksignal/app/dto/TradeDto.java
  back/src/main/java/com/thered/stocksignal/app/dto/kis/KisAccountDto.java
  back/src/main/java/com/thered/stocksignal/app/dto/kis/KisSocketDto.java
  back/src/main/java/com/thered/stocksignal/config/WebSocketConfig.java
  back/src/main/java/com/thered/stocksignal/domain/entity/ScenarioCondition.java
  back/src/main/java/com/thered/stocksignal/domain/entity/Trade.java
  back/src/main/java/com/thered/stocksignal/domain/entity/User.java
  back/src/main/java/com/thered/stocksignal/domain/enums/OrderType.java
  back/src/main/java/com/thered/stocksignal/domain/session/UserSession.java
  back/src/main/java/com/thered/stocksignal/handler/WebSocketHandler.java
  back/src/main/java/com/thered/stocksignal/repository/UserRepository.java
  back/src/main/java/com/thered/stocksignal/service/company/CompanyService.java
  back/src/main/java/com/thered/stocksignal/service/company/CompanyServiceImpl.java
  back/src/main/java/com/thered/stocksignal/service/scenario/ScenarioService.java
  back/src/main/java/com/thered/stocksignal/service/scenario/ScenarioServiceImpl.java
  back/src/main/java/com/thered/stocksignal/service/scenario/ScenarioTrade.java
  back/src/main/java/com/thered/stocksignal/service/scenario/ScenarioTradeImpl.java
  back/src/main/java/com/thered/stocksignal/service/trade/TradeServiceImpl.java
  back/src/main/java/com/thered/stocksignal/service/user/UserAccountService.java
  back/src/main/java/com/thered/stocksignal/service/user/UserAccountServiceImpl.java
  back/src/main/java/com/thered/stocksignal/util/DateUtil.java
  back/src/main/java/com/thered/stocksignal/websocket/WebSocketEndpoint.java
  back/src/main/java/com/thered/stocksignal/websocket/WebSocketHandler.java
Labels: FEAT

#61 Back feat 52
  back/src/main/java/com/thered/stocksignal/domain/entity/User.java
  back/src/main/java/com/thered/stocksignal/service/myBalance/MyBalanceServiceImpl.java
Labels: bug

#62 계좌번호 통일성 패치
  back/src/main/java/com/thered/stocksignal/domain/entity/User.java
  back/src/main/java/com/thered/stocksignal/service/myBalance/MyBalanceServiceImpl.java
Labels: bug

#67 [Bug&Update] 카카오 로그인 토큰 타입 추가
  back/src/main/java/com/thered/stocksignal/app/controller/KakaoLoginController.java
Labels: bug

#68 11/15 배포 - 카카오로그인 패치
  back/src/main/java/com/thered/stocksignal/app/controller/KakaoLoginController.java
Labels: bug, FEAT

#72 [UPDATE] 토큰 시간 이슈 + 신규 기능을 위한 API 변경
  back/src/main/java/com/thered/stocksignal/app/controller/KakaoLoginController.java
  back/src/main/java/com/thered/stocksignal/app/controller/UserInfoController.java
  back/src/main/java/com/thered/stocksignal/app/dto/StockDto.java
  back/src/main/java/com/thered/stocksignal/jwt/AppLoginFilter.java
  back/src/main/java/com/thered/stocksignal/jwt/JWTFilter.java
  back/src/main/java/com/thered/stocksignal/jwt/JWTUtil.java
  back/src/main/java/com/thered/stocksignal/service/company/CompanyServiceImpl.java
  back/src/main/java/com/thered/stocksignal/service/user/UserAccountServiceImpl.java
  back/src/main/java/com/thered/stocksignal/websocket/WebSocketHandler.java
Labels: bug

#74 병합중 오류 해결
  back/src/main/java/com/thered/stocksignal/app/controller/KakaoLoginController.java
Labels: bug

#73 [UPDATE] 토큰 시간 이슈 + 신규 기능을 위한 API 변경
  back/src/main/java/com/thered/stocksignal/app/controller/KakaoLoginController.java
  back/src/main/java/com/thered/stocksignal/app/controller/UserInfoController.java
  back/src/main/java/com/thered/stocksignal/app/dto/StockDto.java
  back/src/main/java/com/thered/stocksignal/jwt/AppLoginFilter.java
  back/src/main/java/com/thered/stocksignal/jwt/JWTFilter.java
  back/src/main/java/com/thered/stocksignal/jwt/JWTUtil.java
  back/src/main/java/com/thered/stocksignal/service/company/CompanyServiceImpl.java
  back/src/main/java/com/thered/stocksignal/service/user/UserAccountServiceImpl.java
  back/src/main/java/com/thered/stocksignal/websocket/WebSocketHandler.java
Labels: bug

#77 [FIX] PINGPONG 메시지 예외 처리
  back/src/main/java/com/thered/stocksignal/websocket/WebSocketHandler.java
Labels: bug

#78 [FIX] PINGPONG 메시지 예외 처리
  back/src/main/java/com/thered/stocksignal/websocket/WebSocketHandler.java
Labels: bug
